# Generated by Django 4.2.1 on 2023-05-26 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FootballPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("position", models.CharField(max_length=5, null=True)),
                ("transfer_fee", models.IntegerField()),
                ("club", models.CharField(blank=True,
                                          max_length=13, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Achievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tournament", models.CharField(max_length=100)),
                ("achievement", models.CharField(max_length=250)),
                ("scored_goals", models.IntegerField(default=0)),
                ("appearances", models.IntegerField(default=0)),
                ("clean_sheets", models.IntegerField(blank=True, null=True)),
                (
                    "football_player_achievements",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="diary.footballplayer",
                    ),
                ),
            ],
        ),
    ]
