# Generated by Django 4.2.1 on 2023-05-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='footballplayer',
            name='achievements',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
