# Generated by Django 4.2.1 on 2023-05-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_alter_footballplayer_club_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='appearances',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='clean_sheets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='achievement',
            name='scored_goals',
            field=models.IntegerField(default=0),
        ),
    ]
