# Generated by Django 4.2.1 on 2023-05-22 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_achievement_appearances_achievement_clean_sheets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='clean_sheets',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
